# Generated by Django 4.1.5 on 2023-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notatka',
            name='content',
            field=models.TextField(),
        ),
    ]
