# Generated by Django 4.1.5 on 2023-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='image',
            field=models.ImageField(default="{% static 'wydatki/expense.jpg' %}", upload_to='images'),
            preserve_default=False,
        ),
    ]
