# Generated by Django 4.1.5 on 2023-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0004_theme_theme_one entry per user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
